import Head from "next/head";
import Flex from "src/components/common/Flex";
import Text from "src/components/common/Text";
import useAdminLayout from "src/hooks/useAdminLayout";

const DashboardPage = (props) => {
  useAdminLayout();

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex center width={"100vw"} height={"100vh"}>
        <Text className="text">dash board page</Text>
      </Flex>
    </>
  );
};

export default DashboardPage;
