const LayoutActionsType = {
  UPDATE_GLOBAL_LOADING: "UPDATE_GLOBAL_LOADING",
  OPEN_OR_CLOSE_HEADER: "OPEN_OR_CLOSE_HEADER",
  OPEN_OR_CLOSE_FOOTER: "OPEN_OR_CLOSE_FOOTER",
  OPEN_OR_CLOSE_APP_MENU: "OPEN_OR_CLOSE_APP_MENU",
  TOGGLE_ANCHOR: "TOGGLE_ANCHOR",
};

export default LayoutActionsType;
