const AuthActionsType = {
  UPDATE_LOADING_CATEGORY: "UPDATE_LOADING_CATEGORY",
  UPDATE_CATEGORY_NAME: "UPDATE_CATEGORY_NAME",
  UPDATE_VALIDATE_CATEGORY: "UPDATE_VALIDATE_CATEGORY",
  UPDATE_CATEGORY_PARENT: "UPDATE_CATEGORY_PARENT",
};

export default AuthActionsType;
