const LoginActionTypes = {
  UPDATE_LOGIN_USER_NAME: "UPDATE_LOGIN_USER_NAME",
  UPDATE_LOGIN_PASSWORD: "UPDATE_LOGIN_PASSWORD",
  UPDATE_LOADING_LOGIN: "UPDATE_LOADING_LOGIN",
  UPDATE_VALIDATE_LOGIN: "UPDATE_VALIDATE_LOGIN",
};

export default LoginActionTypes;
