const OrderActionsType = {
  UPDATE_LOADING_ORDER: "UPDATE_LOADING_ORDER",
  UPDATE_ORDER_NAME: "UPDATE_ORDER_NAME",
  UPDATE_VALIDATE_ORDER: "UPDATE_VALIDATE_ORDER",
  UPDATE_ORDER_PARENT: "UPDATE_ORDER_PARENT",
};

export default OrderActionsType;
