const ProductActionsType = {
  UPDATE_LOADING_PRODUCT: "UPDATE_LOADING_PRODUCT",
  UPDATE_PRODUCT_NAME: "UPDATE_PRODUCT_NAME",
  UPDATE_VALIDATE_PRODUCT: "UPDATE_VALIDATE_PRODUCT",
  UPDATE_PRODUCT_PARENT: "UPDATE_PRODUCT_PARENT",
};

export default ProductActionsType;
