const RoleActionsType = {
  UPDATE_LOADING_ROLE: "UPDATE_LOADING_ROLE",
  UPDATE_ROLE_NAME: "UPDATE_ROLE_NAME",
  UPDATE_VALIDATE_ROLE: "UPDATE_VALIDATE_ROLE",
  UPDATE_ROLE_PARENT: "UPDATE_ROLE_PARENT",
};

export default RoleActionsType;
