const AuthActionsType = {
  UPDATE_SIGNUP_USER_NAME: "UPDATE_SIGNUP_USER_NAME",
  UPDATE_SIGNUP_PASSWORD: "UPDATE_SIGNUP_PASSWORD",
  UPDATE_LOADING_SIGNUP: "UPDATE_LOADING_SIGNUP",
  UPDATE_SIGNUP_PASSWORD_CONFIRM: "UPDATE_SIGNUP_PASSWORD_CONFIRM",
  UPDATE_FULL_NAME: "UPDATE_FULL_NAME",
  UPDATE_PHONE_NUMBER: "UPDATE_PHONE_NUMBER",
  UPDATE_EMAIL: "UPDATE_EMAIL",
  UPDATE_VALIDATE: "UPDATE_VALIDATE",
};

export default AuthActionsType;
