const UserActionsType = {
  UPDATE_LOADING_USER: "UPDATE_LOADING_USER",
  UPDATE_USER_NAME: "UPDATE_USER_NAME",
  UPDATE_VALIDATE_USER: "UPDATE_VALIDATE_USER",
  UPDATE_USER_PARENT: "UPDATE_USER_PARENT",
};

export default UserActionsType;
